#ifndef __GAMEKEYSERIAL_H__
#define __GAMEKEYSERIAL_H__

#define MAX_SERIAL_BYTES 200
#define MAX_ARGUMENT_COUNT 2
#define MAX_BIND_COMMANDS 34
#define BIND_CMD_SEGMENTS 3
#define AXIS_CMD_SEGMENTS 8
#define BIND_BUTTON 0
#define BIND_ARG 1
#define BIND_MODE 2

#endif