#ifndef __GAMEKEYSERIAL_H__
#define __GAMEKEYSERIAL_H__

#define MAX_SERIAL_BYTES 370
#define MAX_ARGUMENT_COUNT 2
#define MAX_BIND_COMMANDS 34
#define BIND_CMD_SEGMENTS 6
#define AXIS_CMD_SEGMENTS 8
#define BIND_BUTTON 0
#define BIND_ARG_A 1
#define BIND_ARG_B 2
#define BIND_ARG_C 3
#define BIND_ARG_D 4
#define BIND_MODE 5

#endif